export type Flight = {
  airline_iata: string | null;
  airline_icao: string;
  flight_iata: string | null;
  flight_icao: string;
  flight_number: string;
  dep_iata: string;
  dep_icao: string;
  dep_terminal: string | null;
  dep_gate: string | null;
  dep_time: Date;
  dep_time_utc: Date;
  dep_estimated?: string;
  dep_estimated_utc?: string;
  dep_actual?: string;
  dep_actual_utc?: string;
  arr_iata: string;
  arr_icao: string;
  arr_terminal: string | null;
  arr_gate: string | null;
  arr_baggage: string | null;
  arr_time: string;
  arr_time_utc: string;
  arr_estimated?: string;
  arr_estimated_utc?: string;
  cs_airline_iata: string | null;
  cs_flight_number: string | null;
  cs_flight_iata: string | null;
  status: string;
  duration: number;
  delayed: number | null;
  dep_delayed: number | null;
  arr_delayed: number | null;
  aircraft_icao: string | null;
  arr_time_ts: number;
  dep_time_ts: number;
  arr_estimated_ts?: number;
  dep_estimated_ts?: number;
  arr_actual_ts?: number;
  dep_actual_ts?: number;
};
